python train_inference_attack.py \
    --attack inference3 \
    --complex \
    --gpus 1 \
    --precision 16 \
    --angle_dis_weights output/angle.ckpt \
    --encoder_weights output/complex.ckpt  \
    --inversion_net_weights  output/inv.ckpt \
    --arch resnet56 \
    --dataset cifar10 \
    --batch_size 128 \
    --optimizer adam \
    --lr 0.001 \
    --schedule step \
    --steps 100 150 \
    --step_factor 0.1 \
