python train_inversion_attack.py \
    --attack feature_inversion \
    --gpus 1 \
    --precision 16 \
    --encoder_weights output/base.ckpt  \
    --max_epochs 15 \
    --batch_size 128 \
    --lr 0.0001 \
    --dataset cifar10 \
