python train_inversion_attack.py \
    --attack angle_inversion \
    --encoder_weights output/complex.ckpt \
    --gpus 1 \
    --precision 16 \
    --max_epochs 50 \
    --batch_size 128 \
    --lr 0.0001 \
    --dataset cifar10 \
